var validator = $($formName).validate({
	rules : {
		khh : {required : true},
		khmc : {required : true},
		rh : {required : true},
		khlx : {required : true},
		zjlx : {required : true},
		zjhm : {required : true},
		qfjg : {required : true},
		sfcq : {required : true},
		qfrq : {required : true},
		dqrq : {required : true},
		gltx : {required : true},
		pqdz : {required : true},
		csrq : {required : true},
		xb : {required : true},
		gtspmc : {required : true},
		gtyyzzhm : {required : true},
		zxyzsj : {required : true},
		yydz : {required : true},
		xxdz : {required : true},
		yzbm : {required : true},
		hjdz : {required : true},
		jtdh : {required : true},
		cz : {required : true},
		sj : {required : true},
		dzyx : {required : true},
		gj : {required : true},
		mz : {required : true},
		zzmm : {required : true},
		xl : {required : true},
		xw : {required : true},
		jkzk : {required : true},
		hyzk : {required : true}
	},
	messages : {
		khh : {required : "客户号不能为空"},
		khmc : {required : "客户名称不能为空"},
		rh : {required : "是否入户不能为空"},
		khlx : {required : "客户类型不能为空"},
		zjlx : {required : "证件类型不能为空"},
		zjhm : {required : "证件号码不能为空"},
		qfjg : {required : "签发机构不能为空"},
		sfcq : {required : "是否长期不能为空"},
		qfrq : {required : "签发日期不能为空"},
		dqrq : {required : "到期日期不能为空"},
		gltx : {required : "管理特征不能为空"},
		pqdz : {required : "片区地址不能为空"},
		csrq : {required : "出生日期不能为空"},
		xb : {required : "性别不能为空"},
		gtspmc : {required : "个体商铺名称不能为空"},
		gtyyzzhm : {required : "个体营业执照号码不能为空"},
		zxyzsj : {required : "最新验照时间不能为空"},
		yydz : {required : "营业地址不能为空"},
		xxdz : {required : "详细住址不能为空"},
		yzbm : {required : "邮政编码不能为空"},
		hjdz : {required : "户籍地址不能为空"},
		jtdh : {required : "家庭电话不能为空"},
		cz : {required : "传真不能为空"},
		sj : {required : "手机不能为空"},
		dzyx : {required : "电子邮箱不能为空"},
		gj : {required : "国籍不能为空"},
		mz : {required : "民族不能为空"},
		zzmm : {required : "政治面貌不能为空"},
		xl : {required : "学历不能为空"},
		xw : {required : "学位不能为空"},
		jkzk : {required : "健康状况不能为空"},
		hyzk : {required : "婚姻状况不能为空"}
	},
	errorPlacement : function(error, element) {
		element.after(error);
		if (layout) {
			layout.resizeLayout();
		}
	}
});