/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：com.cardpay.workflow.models.WfProcessRecord.java
 * 日 期：Tue Dec 02 08:59:49 CST 2014
 */
package com.cardpay.workflow.models;

import java.util.Date;

import com.wicresoft.jrad.base.database.model.BaseModel;
import com.wicresoft.jrad.base.database.model.ModelParam;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ModelParam(table = "WF_PROCESS_RECORD")
public class WfProcessRecord extends BaseModel{
	
	private static final long serialVersionUID = 1L;
	
	private Date createDate;
	
	private String isClosed;
	
	private String wfProcessInfo;
	
	private String wfStatusQueueRecord;
	
	public WfProcessRecord() {
		super();
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * @return the isClosed
	 */
	public String getIsClosed() {
		return this.isClosed;
	}
	
	/**
	 * @param isClosed the isClosed to set
	 */
	public void setIsClosed(String value) {
		this.isClosed = value;
	}

	/**
	 * @return the wfProcessInfo
	 */
	public String getWfProcessInfo() {
		return this.wfProcessInfo;
	}
	
	/**
	 * @param wfProcessInfo the wfProcessInfo to set
	 */
	public void setWfProcessInfo(String value) {
		this.wfProcessInfo = value;
	}

	/**
	 * @return the wfStatusQueueRecord
	 */
	public String getWfStatusQueueRecord() {
		return this.wfStatusQueueRecord;
	}
	
	/**
	 * @param wfStatusQueueRecord the wfStatusQueueRecord to set
	 */
	public void setWfStatusQueueRecord(String value) {
		this.wfStatusQueueRecord = value;
	}
}